name: Build Caddy Images

on:
  push:
    branches:
      - 'main'
  schedule:
    # Run at 12:30 on the first of the month
    - cron: "30 12 1 * *"

jobs:
  docker-builder:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        provider:
          # find from https://github.com/caddy-dns
          - digitalocean
          - cloudflare
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3
      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      - name: Build and push
        uses: docker/build-push-action@v5
        with:
          context: .
          push: true
          build-args: |
            PROVIDER=${{ matrix.provider }}
          tags: platun0v/caddy-dns:${{ matrix.provider }}-latest
          cache-from: type=registry,ref=user/app:latest
          cache-to: type=inline
  dockerhub-description:
    name: Copy README to Dockerhub
    runs-on: ubuntu-latest
    steps:
      - name: Checkout for Dockerhub Description
        uses: actions/checkout@v4
      - name: Copy README
        uses: peter-evans/dockerhub-description@v4
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_RWD }}
          repository: platun0v/caddy-dns
          short-description: Caddy images built with different DNS providers
          readme-filepath: ./README.md
          enable-url-completion: true
  keepalive-job:
    name: Keepalive Workflow
    runs-on: ubuntu-latest
    permissions:
      actions: write
    steps:
      - uses: actions/checkout@v4
      - uses: gautamkrishnar/keepalive-workflow@v2
