name: Build Caddy Images

on:
  push:
    branches:
      - 'main'

jobs:
  docker-builder:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        provider:
          - digitalocean
          - cloudflare
    steps:
      -
        name: Checkout
        uses: actions/checkout@v4
      -
        name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3
      -
        name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      -
        name: Build and push
        uses: docker/build-push-action@v5
        with:
          context: .
          push: true
          build-args: |
            PROVIDER=${{ matrix.provider }}
          tags: jaredlander/caddy-dns:digitalocean-latest
          cache-from: type=registry,ref=user/app:latest
          cache-to: type=inline